# Generated by Django 5.0.6 on 2024-07-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0002_cv_image_cv_language_cv_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='language',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='cv',
            name='skills',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='cv',
            name='summary',
            field=models.TextField(max_length=500),
        ),
    ]
