# Generated by Django 5.0.6 on 2024-07-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0003_alter_cv_language_alter_cv_skills_alter_cv_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='summary',
            field=models.TextField(max_length=1000),
        ),
    ]
