# Generated by Django 5.0.6 on 2024-07-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0004_alter_cv_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='language',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='cv',
            name='previouse_work',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='cv',
            name='project',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='cv',
            name='skills',
            field=models.TextField(max_length=1000),
        ),
    ]
