# Generated by Django 5.0.6 on 2024-07-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='location',
            new_name='country',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='eduaction',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='state',
            field=models.CharField(default='', max_length=200),
        ),
    ]
