# Generated by Django 5.0.6 on 2024-07-06 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_rename_location_userinfo_country_userinfo_eduaction_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='eduaction',
            new_name='education',
        ),
    ]
