# Generated by Django 5.0.6 on 2024-07-08 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_rename_eduaction_userinfo_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField(max_length=1000)),
                ('time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
