# Generated by Django 5.0.6 on 2024-07-08 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0004_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
    ]
